# Generated by Django 5.2.8 on 2025-11-26 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltrasonicReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor_name', models.CharField(default='ultrasonic_1', max_length=50)),
                ('distance_cm', models.FloatField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
