# Generated by Django 5.2.8 on 2025-11-26 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_ultrasonicreading'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-scanned_at']},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(default='rfid', max_length=50),
        ),
        migrations.AddField(
            model_name='ultrasonicreading',
            name='bin_name',
            field=models.CharField(default='Bin 1', max_length=100),
        ),
        migrations.AddField(
            model_name='ultrasonicreading',
            name='raw_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BinConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bin 1', max_length=100, unique=True)),
                ('empty_distance_cm', models.FloatField(default=30.0, help_text='Distance (cm) when bin is EMPTY (sensor → floor/lowest point).')),
                ('full_distance_cm', models.FloatField(default=5.0, help_text='Distance (cm) when bin is FULL (sensor → top of stock).')),
                ('max_units', models.PositiveIntegerField(default=10, help_text='Number of items when bin is considered FULL.')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_configs', to='inventory.item')),
            ],
        ),
    ]
