# Generated by Django 5.2.8 on 2025-11-26 23:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_stockmovement_options_stockmovement_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='scanned_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
