# Generated by Django 5.2.8 on 2025-11-27 00:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stockmovement_scanned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='sku',
            field=models.CharField(blank=True, help_text='Stock Keeping Unit or unique code for the item.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='scanned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When this movement happened (can be backdated for historical data).'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('rfid', 'RFID Scanner'), ('manual', 'Manual Capture'), ('ultrasonic', 'Ultrasonic Sensor'), ('other', 'Other')], default='rfid', max_length=50),
        ),
    ]
